### ISSUE TITLE
哟

### ISSUE THREAD

**Issue by xxxifan** [Feelinging/FEPopupMenuController#1]
什么情况

**Comment by isaced** [comment]
就这个咯～

![design](https://cloud.githubusercontent.com/assets/2088605/12670773/0bef80ee-c6a6-11e5-8d7d-458d0304908a.png)

**Comment by xxxifan** [comment]
搞的真快-。-      我过几天再做这个咯

**Comment by xxxifan** [comment]
哦  我是说organization     建的免费的？

**Comment by isaced** [comment]
是的

**Comment by xxxifan** [comment]
公开的啊   我还以为是私有的  大意了
